// ---------------------------------------------------------------------------
// SCAFFOLDING — not yet wired into the game.
// Generated by fix.py as part of the fractional refactor described in
// aliens-todo.txt. This file establishes the target shape; integrating it
// (updating call sites, removing the code it replaces) is a follow-up step
// that should be done with a working local build to verify against.
// ---------------------------------------------------------------------------

#ifndef SIMULATION_COLLIDER_H
#define SIMULATION_COLLIDER_H

#include "math_types.h"
#include "transform.h"

// Pure collision volume. The project's existing AABB::Intersects(...)
// (src/core/math_types.h) already is the right pure-function shape this
// step asks for — Collider is a thin wrapper so gameplay code can attach
// "does this object collide" as data rather than as a virtual method on a
// rendering base class.
struct Collider {
  AABB aabb{};

  [[nodiscard]] bool Intersects(const Transform& self_transform,
                                 const Collider& other,
                                 const Transform& other_transform,
                                 float shrink = 0.65f) const noexcept {
    return aabb.Intersects(self_transform.position.ToVec2f(),
                            other_transform.position.ToVec2f(),
                            other.aabb, shrink);
  }
};

#endif  // SIMULATION_COLLIDER_H
