// ---------------------------------------------------------------------------
// SCAFFOLDING — not yet wired into the game.
// Generated by fix.py as part of the fractional refactor described in
// aliens-todo.txt. This file establishes the target shape; integrating it
// (updating call sites, removing the code it replaces) is a follow-up step
// that should be done with a working local build to verify against.
// ---------------------------------------------------------------------------

#ifndef SIMULATION_GAME_OBJECT_H
#define SIMULATION_GAME_OBJECT_H

#include <cstdint>

#include "collider.h"
#include "motion.h"
#include "renderable.h"
#include "transform.h"

// Composition root for anything that exists in the game world.
//
// Migration plan for Sprite / Alien / Projectile / Bonus
// (src/entities/sprites.h):
//   1. New entity types are built from GameObject + whichever of the four
//      optional components they need (a static background star has a
//      Transform + Renderable and nothing else; a bullet adds Motion and
//      Collider; only things with real per-type *behaviour* — fleet AI,
//      player input handling — get a dedicated class, and that class
//      *holds* a GameObject rather than deriving from a shared virtual
//      Sprite base).
//   2. Existing Sprite/Projectile/Bonus keep working unmodified while new
//      code adopts GameObject; there is no flag day.
//   3. Once every call site that currently does
//        `const Sprite& other` / `dynamic_cast` / virtual Sprite::Draw()
//      has an equivalent GameObject-based path, Sprite's virtual hierarchy
//      can be deleted.
struct GameObject {
  Transform transform{};
  Motion motion{};
  Collider collider{};
  Renderable renderable{};
  bool active{true};

  void Update() noexcept {
    if (active) transform.position = motion.Integrate(transform.position);
  }

  void Draw() const {
    if (active) renderable.Draw(transform);
  }
};

#endif  // SIMULATION_GAME_OBJECT_H
