// ---------------------------------------------------------------------------
// SCAFFOLDING — not yet wired into the game.
// Generated by fix.py as part of the fractional refactor described in
// aliens-todo.txt. This file establishes the target shape; integrating it
// (updating call sites, removing the code it replaces) is a follow-up step
// that should be done with a working local build to verify against.
// ---------------------------------------------------------------------------

#ifndef SIMULATION_MOTION_H
#define SIMULATION_MOTION_H

#include "math_types.h"
#include "transform.h"

// Pure velocity state + the integration rule. No inheritance, no virtual
// dispatch: anything that moves owns one of these and calls Integrate()
// from the fixed-timestep simulation step (see game_loop.h).
struct Motion {
  Coord velocity{};

  [[nodiscard]] constexpr Coord Integrate(Coord position) const noexcept {
    return position + velocity;
  }
};

#endif  // SIMULATION_MOTION_H
