// ---------------------------------------------------------------------------
// SCAFFOLDING — not yet wired into the game.
// Generated by fix.py as part of the fractional refactor described in
// aliens-todo.txt. This file establishes the target shape; integrating it
// (updating call sites, removing the code it replaces) is a follow-up step
// that should be done with a working local build to verify against.
// ---------------------------------------------------------------------------

#ifndef SIMULATION_RENDERABLE_H
#define SIMULATION_RENDERABLE_H

#include "pix.h"
#include "transform.h"

// Pure rendering data. No virtual Draw(): the renderer walks a list of
// (Transform, Renderable) pairs and draws each one the same way, instead
// of every gameplay type overriding a virtual Sprite::Draw().
struct Renderable {
  const Pix* pix{nullptr};

  void Draw(const Transform& transform) const {
    if (pix) pix->Draw(transform.position, transform.rotation_deg);
  }
};

#endif  // SIMULATION_RENDERABLE_H
