// ---------------------------------------------------------------------------
// SCAFFOLDING — not yet wired into the game.
// Generated by fix.py as part of the fractional refactor described in
// aliens-todo.txt. This file establishes the target shape; integrating it
// (updating call sites, removing the code it replaces) is a follow-up step
// that should be done with a working local build to verify against.
// ---------------------------------------------------------------------------

#ifndef SIMULATION_TRANSFORM_H
#define SIMULATION_TRANSFORM_H

#include "math_types.h"

// Pure spatial state. Every GameObject that occupies space in the world
// has one of these; it knows nothing about rendering or collision.
struct Transform {
  Coord position{};
  float rotation_deg{0.0f};
};

#endif  // SIMULATION_TRANSFORM_H
