// ---------------------------------------------------------------------------
// SCAFFOLDING — not yet wired into the game.
// Generated by fix.py as part of the fractional refactor described in
// aliens-todo.txt. This file establishes the target shape; integrating it
// (updating call sites, removing the code it replaces) is a follow-up step
// that should be done with a working local build to verify against.
// ---------------------------------------------------------------------------

#ifndef CORE_TASK_QUEUE_H
#define CORE_TASK_QUEUE_H

#include <condition_variable>
#include <functional>
#include <mutex>
#include <queue>
#include <thread>
#include <vector>

// Worker pool for non-real-time jobs only: asset preparation, procedural
// generation, audio preparation, high-score I/O. Gameplay state must never
// be touched from these threads — the main thread owns simulation, input,
// and render submission exclusively (see aliens-todo.txt, item 5). Tasks
// posted here should only read immutable inputs and write results back
// through a mechanism the main thread picks up on its own schedule (e.g.
// std::future, as HighScores::SaveAsync already does), never by mutating
// shared gameplay objects directly.
class TaskQueue {
 public:
  explicit TaskQueue(std::size_t worker_count = 2) {
    workers_.reserve(worker_count);
    for (std::size_t i = 0; i < worker_count; ++i) {
      workers_.emplace_back([this] { WorkerLoop(); });
    }
  }

  ~TaskQueue() {
    {
      std::lock_guard<std::mutex> lock(mutex_);
      stopping_ = true;
    }
    cv_.notify_all();
    for (auto& worker : workers_) {
      if (worker.joinable()) worker.join();
    }
  }

  TaskQueue(const TaskQueue&) = delete;
  TaskQueue& operator=(const TaskQueue&) = delete;

  void Post(std::function<void()> task) {
    {
      std::lock_guard<std::mutex> lock(mutex_);
      tasks_.push(std::move(task));
    }
    cv_.notify_one();
  }

 private:
  void WorkerLoop() {
    for (;;) {
      std::function<void()> task;
      {
        std::unique_lock<std::mutex> lock(mutex_);
        cv_.wait(lock, [this] { return stopping_ || !tasks_.empty(); });
        if (stopping_ && tasks_.empty()) return;
        task = std::move(tasks_.front());
        tasks_.pop();
      }
      task();
    }
  }

  std::vector<std::thread> workers_;
  std::queue<std::function<void()>> tasks_;
  std::mutex mutex_;
  std::condition_variable cv_;
  bool stopping_{false};
};

#endif  // CORE_TASK_QUEUE_H
