#include <algorithm>
#include <cstdint>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <string>
#include <vector>

namespace {
std::vector<uint8_t> ReadBinaryFile(const std::string& path) {
  std::ifstream file(path, std::ios::binary | std::ios::ate);
  if (!file.is_open()) return {};
  const std::streamsize size = file.tellg();
  if (size <= 0) return {};
  file.seekg(0, std::ios::beg);
  std::vector<uint8_t> buffer(static_cast<size_t>(size));
  file.read(reinterpret_cast<char*>(buffer.data()), size);
  return buffer;
}
}  // namespace

int main() {
  std::ofstream out("src/platform/embedded_assets.cc");
  if (!out.is_open()) {
    std::cerr << "Error: Unable to open src/platform/embedded_assets.cc\n";
    return 1;
  }

  out << "// Auto-generated by tools/bake_assets.cc (C++20 Embedded Binary "
         "Assets)\n";
  out << "#include \"embedded_assets.h\"\n\n";
  out << "namespace {\n\n";

  const struct PngEntry {
    const char* var_name;
    const char* path;
  } pngs[] = {
      {"png_player", "assets/png/player.png"},
      {"png_player_alt", "assets/png/nave-extra.png"},
      {"png_bullet", "assets/png/bullet.png"},
      {"png_bomb", "assets/png/bomb.png"},
      {"png_bonus_fire", "assets/png/bonus_fire.png"},
      {"png_bonus_shield", "assets/png/bonus_shield.png"},
      {"png_bonus_speed", "assets/png/bonus_speed.png"},
      {"png_bonus_multi", "assets/png/bonus_multi.png"},
      {"png_bonus_nuke", "assets/png/bonus_nuke.png"},
      {"png_alien1", "assets/png/alien1.png"},
      {"png_alien2", "assets/png/alien2.png"},
      {"png_alien3", "assets/png/alien3.png"},
      {"png_alien4", "assets/png/alien4.png"},
      {"png_alien5", "assets/png/alien5.png"},
      {"png_alien6", "assets/png/alien6.png"},
      {"png_alien7", "assets/png/alien7.png"},
      {"png_alien8", "assets/png/alien8.png"},
      {"png_alien9", "assets/png/alien9.png"},
      {"png_alien10", "assets/png/alien10.png"},
      {"png_alien11", "assets/png/alien11.png"},
      {"png_alien12", "assets/png/alien12.png"},
      {"png_alien13", "assets/png/alien13.png"},
      {"png_alien14", "assets/png/alien14.png"},
      {"png_alien15", "assets/png/alien15.png"},
  };

  for (const auto& entry : pngs) {
    auto data = ReadBinaryFile(entry.path);
    out << "alignas(16) static const uint8_t " << entry.var_name << "["
        << std::max<size_t>(1, data.size()) << "] = {\n";
    for (size_t i = 0; i < data.size(); ++i) {
      out << "0x" << std::hex << std::setw(2) << std::setfill('0')
          << static_cast<int>(data[i]) << ",";
      if ((i + 1) % 32 == 0)
        out << "\n";
      else
        out << " ";
    }
    if (data.empty()) out << "0x00";
    out << std::dec << "\n};\n\n";
  }

  out << "} // namespace\n\n";

  out << "namespace EmbeddedImages {\n\n";
  out << "std::pair<std::span<const uint8_t>, Coord> GetSpriteData(SpriteId "
         "id) {\n";
  out << "    switch (id) {\n";
  out << "    case SpriteId::Player:       return { png_player, Coord(76, 76) "
         "};\n";
  out << "    case SpriteId::PlayerAlt:    return { png_player_alt, Coord(76, "
         "76) };\n";
  out << "    case SpriteId::Bullet:       return { png_bullet, Coord(20, 44) "
         "};\n";
  out << "    case SpriteId::Bomb:         return { png_bomb, Coord(26, 26) "
         "};\n";
  // Bonuses scaled +20% (from 28x28 to 34x34)
  out << "    case SpriteId::BonusFire:    return { png_bonus_fire, Coord(41, "
         "41) };\n";
  out << "    case SpriteId::BonusShield:  return { png_bonus_shield, "
         "Coord(41, 41) };\n";
  out << "    case SpriteId::BonusSpeed:   return { png_bonus_speed, Coord(41, "
         "41) };\n";
  out << "    case SpriteId::BonusMulti:   return { png_bonus_multi, Coord(41, "
         "41) };\n";
  out << "    case SpriteId::BonusNuke:    return { png_bonus_nuke, Coord(41, "
         "41) };\n";
  // Alien vessels scaled +20% (from 70x70 to 84x84) for prominent pilot &
  // cockpit visibility
  out << "    case SpriteId::Alien1:       return { png_alien1, Coord(84, 84) "
         "};\n";
  out << "    case SpriteId::Alien2:       return { png_alien2, Coord(84, 84) "
         "};\n";
  out << "    case SpriteId::Alien3:       return { png_alien3, Coord(84, 84) "
         "};\n";
  out << "    case SpriteId::Alien4:       return { png_alien4, Coord(84, 84) "
         "};\n";
  out << "    case SpriteId::Alien5:       return { png_alien5, Coord(84, 84) "
         "};\n";
  out << "    case SpriteId::Alien6:       return { png_alien6, Coord(84, 84) "
         "};\n";
  out << "    case SpriteId::Alien7:       return { png_alien7, Coord(84, 84) "
         "};\n";
  out << "    case SpriteId::Alien8:       return { png_alien8, Coord(84, 84) "
         "};\n";
  out << "    case SpriteId::Alien9:       return { png_alien9, Coord(84, 84) "
         "};\n";
  out << "    case SpriteId::Alien10:      return { png_alien10, Coord(84, 84) "
         "};\n";
  out << "    case SpriteId::Alien11:      return { png_alien11, Coord(84, 84) "
         "};\n";
  out << "    case SpriteId::Alien12:      return { png_alien12, Coord(84, 84) "
         "};\n";
  out << "    case SpriteId::Alien13:      return { png_alien13, Coord(84, 84) "
         "};\n";
  out << "    case SpriteId::Alien14:      return { png_alien14, Coord(84, 84) "
         "};\n";
  out << "    case SpriteId::Alien15:      return { png_alien15, Coord(84, 84) "
         "};\n";
  out << "    default:                     return { {}, Coord(0, 0) };\n";
  out << "    }\n";
  out << "}\n\n";
  out << "} // namespace EmbeddedImages\n";

  return 0;
}
