// ---------------------------------------------------------------------------
// SCAFFOLDING — not yet wired into the game.
// Generated by fix.py as part of the fractional refactor described in
// aliens-todo.txt. This file establishes the target shape; integrating it
// (updating call sites, removing the code it replaces) is a follow-up step
// that should be done with a working local build to verify against.
// ---------------------------------------------------------------------------

#ifndef APPLICATION_APPLICATION_H
#define APPLICATION_APPLICATION_H

#include "config.h"
#include "game_context.h"
#include "highscore.h"
#include "score.h"
#include "sdl_audio.h"
#include "stars.h"
#include "telemetry.h"

// Owns the subsystems that GameContext::CreateDefault() currently pulls
// from ::Instance() singletons. An Application instance is meant to live
// exactly once, at the top of main(), and be threaded down explicitly.
//
// Migration plan for the Config / SoundManager / Score / HighScores /
// StarsFields / Telemetry singletons:
//   1. Each of those classes keeps its Instance() accessor for now — this
//      struct does not change how they're constructed today (their
//      constructors are private and Instance() is still the only way to
//      get one), so nothing here changes runtime behaviour yet.
//   2. Real removal of the singleton pattern means, per class:
//      making the constructor public, deleting the static Instance()
//      method, and updating every call site to use the reference held
//      here (or GameContext's, one hop further down). That touches call
//      sites across main.cc, menu.cc and the entity managers, so it should
//      be done one subsystem at a time, each verified with a local build,
//      not all at once.
//   3. A GameContext built from a real Application (GameContext::From, to
//      be added next to CreateDefault) is what makes it possible to run
//      more than one game instance (tests, replay, headless simulation).
struct Application {
  Config& config = Config::Instance();
  SoundManager& audio = SoundManager::Instance();
  Score& score = Score::Instance();
  HighScores& highscores = HighScores::Instance();
  StarsFields& stars = StarsFields::Instance();
  Telemetry& telemetry = Telemetry::Instance();

  [[nodiscard]] GameContext ToGameContext() const {
    return GameContext{config, audio, score, highscores, stars, telemetry};
  }
};

#endif  // APPLICATION_APPLICATION_H
