// ---------------------------------------------------------------------------
// SCAFFOLDING — not yet wired into the game.
// Generated by fix.py as part of the fractional refactor described in
// aliens-todo.txt. This file establishes the target shape; integrating it
// (updating call sites, removing the code it replaces) is a follow-up step
// that should be done with a working local build to verify against.
// ---------------------------------------------------------------------------

#ifndef APPLICATION_GAME_LOOP_H
#define APPLICATION_GAME_LOOP_H

#include <algorithm>
#include <chrono>

// Fixed-timestep loop with render interpolation, exactly the shape
// described in aliens-todo.txt: gameplay simulation runs at a constant
// rate regardless of display refresh rate or OS hiccups (desktop
// compositor work, wallpaper changes, background processes), and the
// renderer interpolates between the last two simulation snapshots instead
// of ever changing simulation speed to chase frame rate. This is what
// actually removes stutter/tearing perception — not raising process
// priority or trying to lock to 60/120/144 Hz.
//
// Usage (once wired into main.cc's CombatSession loop):
//
//   FixedTimestepLoop loop(std::chrono::milliseconds(8));  // 125 Hz sim
//   while (!quit) {
//     poll_events();
//     loop.Advance([&](){ simulation.Update(); });   // 0..N sim steps
//     renderer.Render(simulation.Snapshot(), loop.InterpolationAlpha());
//   }
//
// A single Advance() call can run zero, one, or several simulation steps
// depending on how much wall-clock time elapsed, but it always caps the
// number of catch-up steps so a long stall (e.g. the window being dragged)
// can't turn into a death spiral of simulation trying to "catch up".
class FixedTimestepLoop {
 public:
  using Clock = std::chrono::steady_clock;

  explicit FixedTimestepLoop(std::chrono::nanoseconds step,
                              int max_steps_per_frame = 5) noexcept
      : step_(step),
        max_steps_per_frame_(max_steps_per_frame),
        previous_(Clock::now()) {}

  // Calls simulate() zero or more times, each representing exactly one
  // fixed timestep. Returns the number of steps actually run.
  template <typename SimulateFn>
  int Advance(SimulateFn&& simulate) {
    const auto now = Clock::now();
    accumulator_ += now - previous_;
    previous_ = now;

    int steps_run = 0;
    while (accumulator_ >= step_ && steps_run < max_steps_per_frame_) {
      simulate();
      accumulator_ -= step_;
      ++steps_run;
    }
    // If we hit the cap, drop the remaining backlog rather than let it
    // compound: better to visibly skip ahead once than to spiral forever.
    if (steps_run == max_steps_per_frame_) {
      accumulator_ = std::min(accumulator_, step_);
    }
    return steps_run;
  }

  // How far between the last simulated state and the next one the
  // renderer should interpolate, in [0, 1).
  [[nodiscard]] double InterpolationAlpha() const noexcept {
    return static_cast<double>(accumulator_.count()) /
           static_cast<double>(step_.count());
  }

 private:
  std::chrono::nanoseconds step_;
  int max_steps_per_frame_;
  Clock::time_point previous_;
  std::chrono::nanoseconds accumulator_{0};
};

#endif  // APPLICATION_GAME_LOOP_H
